version: '2'
services:
  mongo:
    image: "mongo:3"
    volumes:
      - /graylog/data/mongo:/data/db
  elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - /graylog/data/elasticsearch:/usr/share/elasticsearch/data
  graylog:
    image: graylog2/server:2.1.0-3
    volumes:
      - /graylog/data/journal:/usr/share/graylog/data/journal
      - /graylog/config:/usr/share/graylog/data/config
    environment:
      GRAYLOG_PASSWORD_SECRET: Thisisalongstoryandmay1123haveABC
      GRAYLOG_ROOT_PASSWORD_SHA2: d09359b9516c61f5a764632a69a30adde59fcc80ec35120dbe243af34fcb0b40
      GRAYLOG_WEB_ENDPOINT_URI: http://10.5.5.100:9000/api   # Must be real IP due to CORS restrictions can not use 0.0.0.0
    depends_on:
     - mongo
     - elasticsearch
    ports:
     - "9000:9000"
     - "514:514"
     - "1514:1514"
     - "514/udp:514/udp"
     - "5555/udp:5555/udp"
